version: '3.8'

services:
  app:
    build: .
    container_name: shortyapp
    ports:
      - "3050:3000"
    networks:
      - shorty-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: shorty-ngrok
    command: http --url=growing-grub-crisp.ngrok-free.app 3050
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    networks:
      - shorty-network
    depends_on:
      - app

networks:
  shorty-network:
    driver: bridge 