version: '3.8'

services:
  app:
    build: .
    container_name: shortyapp
    ports:
      - "3050:3000"
    networks:
      - shorty-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: shorty-ngrok
    command: http --url=growing-grub-crisp.ngrok-free.app --authtoken ${NGROK_AUTH_TOKEN} app:3000
    ports:
      - "4041:4040"
    networks:
      - shorty-network
    depends_on:
      - app

networks:
  shorty-network:
    driver: bridge 